sonar.projectKey=Joaquinmendez2002-maker_Ucv-ate-si-lab-05
sonar.organization=joaquinmendez2002-maker
sonar.host.url=https://sonarcloud.io

# Puedes dejar estos sin el numeral (#) para que se vean bien en la plataforma
sonar.projectName=Ucv-ate-si-lab-05
sonar.projectVersion=1.0

# Esta línea es obligatoria, le dice que analice todo en esta carpeta
sonar.sources=.