sonar.projectKey=Joaquinmendez2002-maker_Ucv-ate-si-lab-05
sonar.organization=joaquinmendez2002-maker
sonar.host.url=https://sonarcloud.io

sonar.projectName=Ucv-ate-si-lab-05
sonar.projectVersion=1.0

sonar.sources=.
# Esta es la nueva línea mágica que evita que el escáner colapse:
sonar.exclusions=**/.venv/**,**/__pycache__/**